#Example of IBM Cloud storage class for Mongo DB Community Edition
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodbsc
parameters:
  billingType: hourly
  classVersion: "2"
  fsType: ext4
  sizeIOPSRange: |-
    [100-100]Gi:[2000-2000]
  type: Performance
provisioner: ibm.io/ibmc-block
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer